#https://starship.rs/config/

[character]
success_symbol = "➜"
error_symbol = "✗"
vicmd_symbol = ""

[package]
disabled = true

[git_status]
stashed='⍟$count'

[nodejs]
style = "fg:#026e00"

# ln -s /real/path /linked/path
# ln -s /Users/xxx/dotfiles/config/starship.toml /Users/xxx/.config/starship.toml