git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  sidePanelWidth: 0.16 # Default is 0.333
  showIcons: true
  nerdFontsVersion: "3"
  
# ln -s /real/path /linked/path
# 
