set -g default-terminal "tmux-256color"
set -as terminal-features "xterm-256color:RGB"

set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g allow-passthrough on
set -g focus-events on

set -w -g mode-keys vi
set -s escape-time 0
set -g mouse on

set -g set-titles on
set -g set-titles-string "#T"

set -w -g automatic-rename on
set -w -g monitor-activity on
set -g visual-activity on

set -g base-index 1
set -w -g pane-base-index 1
set -g renumber-windows on

set -g status-position bottom
set -g status-justify left
set -g status-style bg=#1e1e1e,fg=#d4d4d4
set -g status-left-length 40
set -g status-right-length 90

set -g status-left '#[bg=colour7]#[fg=colour0]#{?client_prefix,#[bg=colour2],} #S #[bg=colour0]#[fg=colour7]#{?client_prefix,#[fg=colour2],}#{?window_zoomed_flag, 🔍 ,}#[fg=colour1] 󰱴 '
set -g status-right '#[fg=colour3]#[bg=colour3]#[fg=colour0]  #h #[bg=colour3]#[fg=colour1]#[bg=colour1]#[fg=colour0] %a %b %d %l:%M %p '

set -w -g window-status-style fg=colour1,bg=colour0
set -w -g window-status-current-style fg=colour0,bg=colour1
set -w -g window-status-format "[ #I: #W #{?window_flags,#{window_flags} ,}]"
set -w -g window-status-current-format "#[fg=colour0]#[bg=colour4]#[fg=colour7]#[bg=colour4] #I #{?window_flags,#{window_flags},} #[fg=colour7] #W #[fg=colour4]#[bg=colour0]"

# Reload config with r
bind-key r source-file ~/.tmux.conf \; display "Config Reloaded!"

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

bind-key g display-popup -E -w 90% -h 90% "lazygit"
bind-key C-t display-popup -E -w 80% -h 80% "$SHELL"

# split panes using | and -
bind-key | split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi ] send-keys -X copy-selection

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run -b '~/.tmux/plugins/tpm/tpm'
